class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'vi': {
      'settings_title': 'Cài đặt',
      'appearance_section': 'GIAO DIỆN',
      'dark_mode': 'Chế độ tối (Dark Mode)',
      'dark_mode_subtitle': 'Sử dụng giao diện tối để bảo vệ mắt',
      'display_font': 'Font chữ hiển thị',
      'display_font_subtitle': 'Tùy chỉnh font chữ cho phần đọc',
      'language': 'Ngôn ngữ / Language',
      'language_subtitle': 'Chọn ngôn ngữ hiển thị',
      'ai_config_section': 'CẤU HÌNH AI',
      'translation_model': 'Mô hình dịch thuật',
      'translation_model_subtitle': 'Chọn mô hình ngôn ngữ chính',
      'manage_models': 'Quản lý Model đã tải',
      'manage_models_subtitle': 'model đã cài đặt',
      'translation_config_section': 'CẤU HÌNH DỊCH THUẬT',
      'project_folder': 'Thư mục dự án',
      'not_configured': 'Chưa cấu hình',
      'footer_credit': 'FluxOrigin v1.0.0 - Made with ☕ by d-init-d',
      'download_success': 'Tải model thành công!',
      'download_fail': 'Tải model thất bại.',
      'delete_model_confirm': 'Xác nhận xóa',
      'delete_model_question': 'Bạn có chắc muốn xóa model',
      'cancel': 'Hủy',
      'delete': 'Xóa',
      'deleted_model': 'Đã xóa model',
      'delete_fail': 'Xóa model thất bại',
      'manage_models_title': 'Quản lý Model đã tải',
      'no_models_installed': 'Chưa có model nào được tải',
      'delete_model_tooltip': 'Xóa model',
      'close': 'Đóng',
      // AI Provider Settings
      'ai_provider_subtitle': 'Chọn nguồn AI để sử dụng cho dịch thuật',
      'ollama_url_subtitle':
          'Địa chỉ kết nối tới Ollama (mặc định: http://localhost:11434)',
      'lmstudio_url_subtitle':
          'Địa chỉ kết nối tới LM Studio (mặc định: http://localhost:1234)',
      'checking_connection': 'Đang kiểm tra...',
      'check_connection': 'Kiểm tra kết nối',
      'lmstudio_note':
          'LM Studio: Hãy đảm bảo đã bật Local Server trong LM Studio và đã load model trước khi sử dụng.',
      'no_models_check_connection':
          'Chưa có model nào. Hãy kiểm tra kết nối Ollama.',
      'select_from_models': 'Chọn từ {count} model đã cài đặt',
      'no_model_available': 'Không có model',
      'models_installed_count': '{count} model đã cài đặt',
      // Connection messages
      'ollama_connection_success':
          'Kết nối Ollama thành công! Đã tìm thấy @count model.',
      'lmstudio_connection_success':
          'Kết nối LM Studio thành công! Đã tìm thấy @count model.',
      'connection_error_timeout':
          'Hết thời gian chờ. Kiểm tra lại URL hoặc server có đang chạy không.',
      'connection_error_connect':
          'Không thể kết nối tới server. Hãy đảm bảo server đang chạy.',
      'connection_error_status': 'Lỗi: Server trả về mã @code',
      'connection_error_generic': 'Lỗi kết nối: Không thể kết nối tới server.',
      // Sidebar
      'sidebar_translate': 'Dịch thuật',
      'sidebar_history': 'Lịch sử',
      'sidebar_dictionary': 'Từ điển',
      'sidebar_settings': 'Cài đặt',
      'sidebar_batch': 'Dịch hàng loạt',
      // Translate Screen
      'enter_text_placeholder': 'Nhập văn bản cần dịch...',
      'translate_now': 'Dịch ngay',
      'translating': 'Đang dịch...',
      'start_translation': 'BẮT ĐẦU DỊCH',
      'continue_translation': 'TIẾP TỤC DỊCH',
      'pause': 'Tạm dừng',
      'cancel_action': 'Hủy bỏ',
      'save_result': 'LƯU KẾT QUẢ',
      'translate_another': 'Dịch file khác',
      'local_dictionary': 'Từ điển cục bộ',
      'processing': 'Đang xử lý...',
      'translation_success': 'Dịch thành công!',
      'error_prefix': 'Lỗi: ',
      'please_configure_project': 'Vui lòng cấu hình thư mục dự án trước!',
      'file_saved_at': 'Đã lưu file tại: ',
      'error_saving_file': 'Lỗi khi lưu file: ',
      'save_result_dialog_title': 'Lưu kết quả dịch',
      'progress': 'Tiến độ: ',
      'delete_progress_tooltip': 'Xóa tiến độ và bắt đầu lại',
      'restart_from_beginning': 'Bắt đầu lại từ đầu',
      'pausing': 'Đang tạm dừng sau đoạn hiện tại...',
      'resuming': 'Đang tiếp tục dịch...',
      'initializing': 'Đang khởi tạo...',
      // Live Preview
      'source_text_panel': 'Văn bản gốc',
      'translated_text_panel': 'Bản dịch',
      'chunk_progress': 'Đoạn',
      'waiting_data': 'Chờ dữ liệu...',
      // History Screen
      'history_title': 'Lịch sử dịch thuật',
      'refresh_tooltip': 'Làm mới',
      'no_history': 'Chưa có lịch sử dịch',
      'no_history_subtitle': 'Các file đã dịch thành công sẽ hiển thị ở đây',
      'yesterday': 'Hôm qua',
      'days_ago': 'ngày trước',
      // Dictionary Screen
      'dictionary_title': 'Từ điển & Thuật ngữ',
      'dictionary_subtitle': 'Quản lý các tệp từ điển cá nhân và chuyên ngành.',
      'add_new': 'Thêm mới',
      'dictionary_name': 'TÊN TỪ ĐIỂN',
      'dictionary_size': 'KÍCH THƯỚC',
      'dictionary_entries': 'SỐ TỪ',
      'showing_dictionaries': 'Hiển thị dictionaries từ điển',
      'no_dictionaries': 'Chưa có từ điển nào',
      'no_dictionaries_subtitle': 'Thêm file .csv vào thư mục dictionary',
      // Batch Translate Screen
      'batch_title': 'Dịch hàng loạt',
      'batch_subtitle': 'Chọn thư mục chứa nhiều file .txt để dịch tự động',
      'batch_pick_folder': 'Chọn thư mục',
      'batch_pick_dictionary': 'Chọn từ điển dùng chung (tùy chọn)',
      'batch_no_folder': 'Chưa chọn thư mục',
      'batch_files_found': 'Tìm thấy {count} file .txt',
      'batch_start': 'BẮT ĐẦU DỊCH HÀNG LOẠT',
      'batch_pause': 'Tạm dừng',
      'batch_skip_existing': 'Bỏ qua file đã có bản dịch',
      'batch_recursive': 'Quét cả thư mục con',
      'batch_report_title': 'Báo cáo dịch hàng loạt',
      'batch_file_label': 'File',
      'batch_status_label': 'Trạng thái',
      'batch_status_pending': 'Chờ',
      'batch_status_running': 'Đang dịch',
      'batch_status_done': 'Xong',
      'batch_status_failed': 'Lỗi',
      'batch_status_skipped': 'Bỏ qua',
      // Upload Dictionary Modal
      'add_dict_title': 'Thêm từ điển mới',
      'dict_name_label': 'Tên hiển thị',
      'dict_name_hint': 'Nhập tên từ điển...',
      'dict_file_label': 'File dữ liệu (.json, .csv)',
      'select_file_btn': 'Chọn file',
      'file_selected': 'Đã chọn file:',
      'upload_btn': 'Thêm từ điển',
      'error_missing_info': 'Vui lòng nhập tên và chọn file',
      'drag_drop_or': 'Kéo và thả file hoặc',
      'browse_files': 'Chọn từ máy',
      'supported_dict_formats': 'Hỗ trợ .csv',
      'unsupported_dict_format_error': 'Chỉ hỗ trợ file .CSV',
      // Common
      'confirm': 'Xác nhận',
      'success': 'Thành công',
      'failed': 'Thất bại',
      'save': 'Lưu',
      'source_text_hint': 'Nhập văn bản cần dịch...',
      'translate_button': 'Dịch',
      'auto_detect': 'Phát hiện ngôn ngữ',
      'copy': 'Sao chép',
      'clear': 'Xóa',
      'source_language': 'Ngôn ngữ nguồn',
      'target_language': 'Ngôn ngữ đích',
      'drag_drop_file': 'Kéo thả tài liệu vào đây',
      'supported_formats': 'Hỗ trợ .TXT, .EPUB',
      'unsupported_format_error': 'Chỉ hỗ trợ file .TXT và .EPUB',
      'drop_file_here': 'Thả file vào đây',
      'choose_file': 'Chọn file',
      'upload_dictionary_placeholder': 'Tải lên từ điển của bạn',
      'selected': 'Đã chọn',
      'change_file': 'Thay đổi',
      'local_mode_hint':
          'Nếu không tải lên từ điển, mặc định AI sẽ tự tạo mới từ điển cục bộ (không dùng Internet).',
      'ai_auto_mode': 'AI Tự động (Online)',
      'ai_auto_hint':
          'Hệ thống có quyền truy cập internet để hoàn thành từ điển.',
      'error_picking_file': 'Lỗi chọn file: ',
      'lang_en': 'Tiếng Anh',
      'lang_vi': 'Tiếng Việt',
      'lang_cn': 'Tiếng Trung',
      'default_label': 'Mặc định',
      // Translation Status Messages
      'status_restoring_progress':
          'Đã tìm thấy bản lưu cũ. Đang khôi phục tiến độ...',
      'status_reading_file': 'Đang đọc file gốc...',
      'status_analyzing': 'Đang phân tích và chia nhỏ văn bản...',
      'status_detecting_genre': 'AI đang đọc thử để xác định thể loại...',
      'status_creating_glossary': 'AI đang tạo từ điển tên riêng...',
      'status_translating': 'Đang dịch đoạn',
      'status_paused': 'Đã tạm dừng. Tiến độ đã được lưu.',
      'status_merging': 'Đang ghép file kết quả...',
      'status_completed': 'Dịch hoàn tất!',
      'status_error': 'Lỗi khi dịch đoạn',
      'status_using_user_glossary': 'Đang dùng từ điển của bạn...',
      'status_batch_progress': 'Đang dịch hàng loạt: {current}/{total} file',
      'status_batch_done': 'Hoàn tất: {success} thành công, {failed} thất bại',
      'report_inappropriate_content': 'Báo cáo nội dung không phù hợp',
      // Ollama Connection Error Dialog
      'ollama_connection_error_title': 'Lỗi kết nối',
      'ollama_connection_error_body':
          'Không thể kết nối tới Ollama. Vui lòng kiểm tra:\n• Ollama đã được cài đặt chưa?\n• Ollama đang chạy chưa?',
      'check_settings_hint': 'Mở Cài đặt để kiểm tra cấu hình',
      'ok_button': 'OK',
    },
    'en': {
      'settings_title': 'Settings',
      'appearance_section': 'APPEARANCE',
      'dark_mode': 'Dark Mode',
      'dark_mode_subtitle': 'Use dark theme to reduce eye strain',
      'display_font': 'Display Font',
      'display_font_subtitle': 'Customize font for reading',
      'language': 'Language / Ngôn ngữ',
      'language_subtitle': 'Choose display language',
      'ai_config_section': 'AI CONFIGURATION',
      'translation_model': 'Translation Model',
      'translation_model_subtitle': 'Select primary language model',
      'manage_models': 'Manage Downloaded Models',
      'manage_models_subtitle': 'models installed',
      'translation_config_section': 'TRANSLATION CONFIG',
      'project_folder': 'Project Folder',
      'not_configured': 'Not configured',
      'footer_credit': 'FluxOrigin v1.0.0 - Made with ☕ by d-init-d',
      'download_success': 'Model downloaded successfully!',
      'download_fail': 'Model download failed.',
      'delete_model_confirm': 'Confirm Delete',
      'delete_model_question': 'Are you sure you want to delete model',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'deleted_model': 'Model deleted',
      'delete_fail': 'Failed to delete model',
      'manage_models_title': 'Manage Downloaded Models',
      'no_models_installed': 'No models installed',
      'delete_model_tooltip': 'Delete model',
      'close': 'Close',
      // AI Provider Settings
      'ai_provider_subtitle': 'Select AI source for translation',
      'ollama_url_subtitle':
          'Ollama connection address (default: http://localhost:11434)',
      'lmstudio_url_subtitle':
          'LM Studio connection address (default: http://localhost:1234)',
      'checking_connection': 'Checking...',
      'check_connection': 'Test Connection',
      'lmstudio_note':
          'LM Studio: Make sure to enable Local Server in LM Studio and load a model before using.',
      'no_models_check_connection':
          'No models found. Please check Ollama connection.',
      'select_from_models': 'Select from {count} installed models',
      'no_model_available': 'No models',
      'models_installed_count': '{count} models installed',
      // Connection messages
      'ollama_connection_success':
          'Ollama connected successfully! Found @count models.',
      'lmstudio_connection_success':
          'LM Studio connected successfully! Found @count models.',
      'connection_error_timeout':
          'Connection timed out. Please check the URL or if the server is running.',
      'connection_error_connect':
          'Cannot connect to server. Please make sure the server is running.',
      'connection_error_status': 'Error: Server returned status @code',
      'connection_error_generic':
          'Connection error: Unable to connect to server.',
      // Sidebar
      'sidebar_translate': 'Translate',
      'sidebar_history': 'History',
      'sidebar_dictionary': 'Dictionary',
      'sidebar_settings': 'Settings',
      'sidebar_batch': 'Batch Translate',
      // Translate Screen
      'enter_text_placeholder': 'Enter text to translate...',
      'translate_now': 'Translate Now',
      'translating': 'Translating...',
      'start_translation': 'START TRANSLATION',
      'continue_translation': 'CONTINUE TRANSLATION',
      'pause': 'Pause',
      'cancel_action': 'Cancel',
      'save_result': 'SAVE RESULT',
      'translate_another': 'Translate another file',
      'local_dictionary': 'Local Dictionary',
      'processing': 'Processing...',
      'translation_success': 'Translation Successful!',
      'error_prefix': 'Error: ',
      'please_configure_project': 'Please configure project folder first!',
      'file_saved_at': 'File saved at: ',
      'error_saving_file': 'Error saving file: ',
      'save_result_dialog_title': 'Save Translation Result',
      'progress': 'Progress: ',
      'delete_progress_tooltip': 'Delete progress and restart',
      'restart_from_beginning': 'Restart from beginning',
      'pausing': 'Pausing after current segment...',
      'resuming': 'Resuming translation...',
      'initializing': 'Initializing...',
      // Live Preview
      'source_text_panel': 'Source Text',
      'translated_text_panel': 'Translation',
      'chunk_progress': 'Chunk',
      'waiting_data': 'Waiting for data...',
      // History Screen
      'history_title': 'Translation History',
      'refresh_tooltip': 'Refresh',
      'no_history': 'No translation history',
      'no_history_subtitle': 'Successfully translated files will appear here',
      'yesterday': 'Yesterday',
      'days_ago': 'days ago',
      // Dictionary Screen
      'dictionary_title': 'Dictionaries & Terms',
      'dictionary_subtitle':
          'Manage personal and specialized dictionary files.',
      'add_new': 'Add New',
      'dictionary_name': 'DICTIONARY NAME',
      'dictionary_size': 'SIZE',
      'dictionary_entries': 'ENTRIES',
      'showing_dictionaries': 'Showing dictionaries',
      'no_dictionaries': 'No dictionaries found',
      'no_dictionaries_subtitle': 'Add .csv files to the dictionary folder',
      // Batch Translate Screen
      'batch_title': 'Batch Translate',
      'batch_subtitle':
          'Select a folder containing multiple .txt files to translate them automatically',
      'batch_pick_folder': 'Choose Folder',
      'batch_pick_dictionary': 'Choose shared dictionary (optional)',
      'batch_no_folder': 'No folder selected',
      'batch_files_found': 'Found {count} .txt files',
      'batch_start': 'START BATCH TRANSLATION',
      'batch_pause': 'Pause',
      'batch_skip_existing': 'Skip files that already have a translation',
      'batch_recursive': 'Scan sub-folders too',
      'batch_report_title': 'Batch Translation Report',
      'batch_file_label': 'File',
      'batch_status_label': 'Status',
      'batch_status_pending': 'Pending',
      'batch_status_running': 'Translating',
      'batch_status_done': 'Done',
      'batch_status_failed': 'Failed',
      'batch_status_skipped': 'Skipped',
      // Upload Dictionary Modal
      'add_dict_title': 'Add New Dictionary',
      'dict_name_label': 'Display Name',
      'dict_name_hint': 'Enter dictionary name...',
      'dict_file_label': 'Data File (.json, .csv)',
      'select_file_btn': 'Select File',
      'file_selected': 'File selected:',
      'upload_btn': 'Add Dictionary',
      'error_missing_info': 'Please enter name and select file',
      'drag_drop_or': 'Drag and drop file or',
      'browse_files': 'Browse',
      'supported_dict_formats': 'Supports .csv',
      'unsupported_dict_format_error': 'Only .CSV files are supported',
      // Common
      'confirm': 'Confirm',
      'success': 'Success',
      'failed': 'Failed',
      'save': 'Save',
      'source_text_hint': 'Enter text to translate...',
      'translate_button': 'Translate',
      'auto_detect': 'Auto Detect',
      'copy': 'Copy',
      'clear': 'Clear',
      'source_language': 'Source Language',
      'target_language': 'Target Language',
      'drag_drop_file': 'Drag and drop file here',
      'supported_formats': 'Supports .TXT, .EPUB',
      'unsupported_format_error': 'Only .TXT and .EPUB files are supported',
      'drop_file_here': 'Drop file here',
      'choose_file': 'Choose File',
      'upload_dictionary_placeholder': 'Upload your dictionary',
      'selected': 'Selected',
      'change_file': 'Change',
      'local_mode_hint':
          'If no dictionary is uploaded, AI will create a local one by default (offline).',
      'ai_auto_mode': 'AI Auto (Online)',
      'ai_auto_hint': 'System has internet access to complete the dictionary.',
      'error_picking_file': 'Error picking file: ',
      'lang_en': 'English',
      'lang_vi': 'Vietnamese',
      'lang_cn': 'Chinese',
      'default_label': 'Default',
      // Translation Status Messages
      'status_restoring_progress': 'Found saved progress. Resuming...',
      'status_reading_file': 'Reading source file...',
      'status_analyzing': 'Analyzing and chunking text...',
      'status_detecting_genre': 'AI is detecting genre...',
      'status_creating_glossary': 'AI is generating glossary...',
      'status_translating': 'Translating chunk',
      'status_paused': 'Paused. Progress saved.',
      'status_merging': 'Merging output files...',
      'status_completed': 'Translation completed!',
      'status_error': 'Error translating chunk',
      'status_using_user_glossary': 'Using your custom glossary...',
      'status_batch_progress': 'Batch progress: {current}/{total} files',
      'status_batch_done': 'Done: {success} succeeded, {failed} failed',
      'report_inappropriate_content': 'Report inappropriate content',
      // Ollama Connection Error Dialog
      'ollama_connection_error_title': 'Connection Error',
      'ollama_connection_error_body':
          'Cannot connect to Ollama. Please check:\n• Is Ollama installed?\n• Is Ollama running?',
      'check_settings_hint': 'Open Settings to check configuration',
      'ok_button': 'OK',
    },
  };

  static String get(String lang, String key) {
    return _localizedValues[lang]?[key] ?? _localizedValues['vi']![key]!;
  }
}
